sonar.organization=matteceejay30
sonar.projectKey=matteceejay_terraform-cicd

# Optional but worth setting for a project this size:
# This is the root directory of the project to be scanned. If you don't set this, SonarQube will scan the entire repository, which can be slow and may include files you don't want to scan.
sonar.sources=.